# Generated by Django 4.2.4 on 2023-08-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0002_alter_pet_group"),
        ("traits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trait",
            name="pets",
            field=models.ManyToManyField(related_name="traits", to="pets.pet"),
        ),
    ]
